name: Website Downloader

on:
  workflow_dispatch: # Memungkinkan input manual saat menjalankan workflow
    inputs:
      website_url:
        description: "Enter the URL of the website to download"
        required: true
        default: "https://example.com"

jobs:
  download-website:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget zip

    - name: Download Website
      run: |
        mkdir -p website
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent "${{ github.event.inputs.website_url }}" -P website

    - name: Create ZIP Archive
      run: |
        cd website
        zip -r ../website-offline.zip .

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website-offline
        path: website-offline.zip
